version: '3'

services:

  subquery-node:
    image: onfinality/subql-node:latest
    depends_on:
      - "postgres"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./bifrost-subql/:/app
    command:
      - -f=/app
      - --local
      - --unsafe
      - --timestamp-field
      - --batch-size=30


  subquery-node-kusama:
    image: onfinality/subql-node:latest
    depends_on:
      - "postgres"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: kusama
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./bifrost-subql/.kusama:/app
    command:
      - -f=/app
      - --local
      - --unsafe
      - --timestamp-field
      - --batch-size=30

  subquery-node-polkadot:
    image: onfinality/subql-node:latest
    depends_on:
      - "postgres"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: polkadot
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./bifrost-subql/.polkadot:/app
    command:
      - -f=/app
      - --local
      - --unsafe
      - --timestamp-field
      - --batch-size=30
