specVersion: 0.2.0
name: bifrost-subql
version: 1.0.0
description: ''
repository: 'https://github.com/bifrost-finance/bifrost-subql.git'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x9eec74d36b41d3bce4122e46c0b370293d6b0462f2efd887d2765d8ee9a3c18b'
  endpoint: 'wss://bifrost-rpc.devnet.liebi.com/ws'
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: vtokenMinting
          kind: substrate/BlockHandler
        - handler: handleVtokenMintingMinted
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: Minted
        - handler: handleVtokenMintingRedeemed
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: Redeemed
        - handler: handleVtokenMintingRebondedByUnlockId
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: RebondedByUnlockId
        - handler: handleVKSMSwap
          kind: substrate/EventHandler
          filter:
            module: zenlinkProtocol
            method: AssetSwap
        - handler: handleVMOVRSwap
          kind: substrate/EventHandler
          filter:
            module: zenlinkProtocol
            method: AssetSwap
        - handler: handleCurrenciesTransferred
          kind: substrate/CallHandler
          filter:
            module: currencies
            method: transfer
            success: true
        - handler: handleCurrenciesTransferred
          kind: substrate/CallHandler
          filter:
            module: tokens
            method: transfer
            success: true
        - handler: handleVtokenRedeemedSuccess
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: RedeemSuccess
        - handler: handleVtokenLiquidity
          kind: substrate/EventHandler
          filter:
            module: zenlinkProtocol
            method: LiquidityAdded
        - handler: handleVtokenLiquidity
          kind: substrate/EventHandler
          filter:
            module: zenlinkProtocol
            method: LiquidityRemoved
        - handler: handleSlp
          kind: substrate/BlockHandler