specVersion: 0.2.0
name: bifrost-subql
version: 1.0.0
description: ''
repository: git@github.com:bifrost-finance/bifrost-subql.git
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x9f28c6a68e0fc9646eff64935684f6eeeece527e37bbe1f213d22caa1d9d6bed'
  endpoint: wss://bifrost-parachain.api.onfinality.io/public-ws
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 318500
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: zenlink
          kind: substrate/BlockHandler
        - handler: zenlinkAssetSwap
          kind: substrate/EventHandler
          filter:
            module: zenlinkProtocol
            method: AssetSwap
        - handler: zenlinkLiquidityAdded
          kind: substrate/EventHandler
          filter:
            module: zenlinkProtocol
            method: LiquidityAdded
        - handler: zenlinkLiquidityRemoved
          kind: substrate/EventHandler
          filter:
            module: zenlinkProtocol
            method: LiquidityRemoved
        - handler: salp
          kind: substrate/BlockHandler
        - handler: vsbond
          kind: substrate/BlockHandler
        - handler: salpContribution
          kind: substrate/BlockHandler
        - handler: handleSalpContributed
          kind: substrate/EventHandler
          filter:
            module: salp
            method: Contributed
        - handler: handleSalpRefunded
          kind: substrate/EventHandler
          filter:
            module: salp
            method: Refunded
        - handler: handleSalpFailed
          kind: substrate/EventHandler
          filter:
            module: salp
            method: Failed
        - handler: handleXtokensTransferred
          kind: substrate/EventHandler
          filter:
            module: xTokens
            method: Transferred
        - handler: handleBalancesTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleBalancesEndowed
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Endowed
        - handler: handleBalancesDustLost
          kind: substrate/EventHandler
          filter:
            module: balances
            method: DustLost
        - handler: handleBalancesReserved
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Reserved
        - handler: handleBalancesUnreserved
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Unreserved
        - handler: handleBalancesBalanceSet
          kind: substrate/EventHandler
          filter:
            module: balances
            method: BalanceSet
        - handler: handleBalancesDeposit
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleBalancesReserveRepatriated
          kind: substrate/EventHandler
          filter:
            module: balances
            method: ReserveRepatriated
        - handler: handleCurrenciesDeposited
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Deposited
        - handler: handleCurrenciesWithdrawn
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Withdrawn
        - handler: handleCurrenciesTransferred
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred
        - handler: handleCurrenciesBalanceUpdated
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: BalanceUpdated
        - handler: handleTokensTransfer
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Transfer
        - handler: handleTokensEndowed
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Endowed
        - handler: handleTokensDustLost
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: DustLost
        - handler: handleTokensReserved
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Reserved
        - handler: handleTokensUnreserved
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Unreserved
        - handler: handleTokensBalanceSet
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: BalanceSet
        - handler: handleTokenIssuerTransferred
          kind: substrate/EventHandler
          filter:
            module: tokenIssuer
            method: Transferred
        - handler: handleTokenIssuerIssued
          kind: substrate/EventHandler
          filter:
            module: tokenIssuer
            method: Issued
        - handler: handleVestingVestingUpdated
          kind: substrate/EventHandler
          filter:
            module: vesting
            method: VestingUpdated
        - handler: handleVestingVestingCompleted
          kind: substrate/EventHandler
          filter:
            module: vesting
            method: VestingCompleted
        - handler: handleSalpLiteIssued
          kind: substrate/EventHandler
          filter:
            module: salpLite
            method: Issued
        - handler: handleSalpLiteRedeemed
          kind: substrate/EventHandler
          filter:
            module: salpLite
            method: Redeemed
        - handler: handleSalpLiteRefunded
          kind: substrate/EventHandler
          filter:
            module: salpLite
            method: Refunded
