specVersion: 0.2.0
name: bifrost-subql
version: 1.0.0
description: ''
repository: git@github.com:bifrost-finance/bifrost-subql.git
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x262e1b2ad728475fd6fe88e62d34c200abe6fd693931ddad144059b1eb884e5b'
  endpoint: wss://hk.p.bifrost-rpc.liebi.com/ws
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleSignedBlock
          kind: substrate/BlockHandler
        - handler: tokens
          kind: substrate/BlockHandler
        - handler: democracy
          kind: substrate/BlockHandler
        - handler: council
          kind: substrate/BlockHandler
        - handler: handleCallExtrinsic
          kind: substrate/CallHandler
        - handler: zenlink
          kind: substrate/BlockHandler
        - handler: zenlinkAssetSwap
          kind: substrate/EventHandler
          filter:
            module: zenlinkProtocol
            method: AssetSwap
        - handler: vsbond
          kind: substrate/BlockHandler
        - handler: handleVsBondAuctionOrderClinchd
          kind: substrate/EventHandler
          filter:
            module: vsBondAuction
            method: OrderClinchd
        - handler: handleXtokensTransferred
          kind: substrate/EventHandler
          filter:
            module: xTokens
            method: Transferred
        - handler: handleXtokensTransferredMultiAssets
          kind: substrate/EventHandler
          filter:
            module: xTokens
            method: TransferredMultiAssets
        - handler: handleBalancesTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleBalancesEndowed
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Endowed
        - handler: handleBalancesDustLost
          kind: substrate/EventHandler
          filter:
            module: balances
            method: DustLost
        - handler: handleBalancesReserved
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Reserved
        - handler: handleBalancesUnreserved
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Unreserved
        - handler: handleBalancesBalanceSet
          kind: substrate/EventHandler
          filter:
            module: balances
            method: BalanceSet
        - handler: handleBalancesDeposit
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleBalancesReserveRepatriated
          kind: substrate/EventHandler
          filter:
            module: balances
            method: ReserveRepatriated
        - handler: handleCurrenciesDeposited
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Deposited
        - handler: handleCurrenciesWithdrawn
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Withdrawn
        - handler: handleCurrenciesTransferred
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred
        - handler: handleCurrenciesBalanceUpdated
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: BalanceUpdated
        - handler: handleTokensTransfer
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Transfer
        - handler: handleTokensEndowed
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Endowed
        - handler: handleTokensDustLost
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: DustLost
        - handler: handleTokensReserved
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Reserved
        - handler: handleTokensUnreserved
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Unreserved
        - handler: handleTokensBalanceSet
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: BalanceSet
        - handler: handleTokenIssuerTransferred
          kind: substrate/EventHandler
          filter:
            module: tokenIssuer
            method: Transferred
        - handler: handleTokenIssuerIssued
          kind: substrate/EventHandler
          filter:
            module: tokenIssuer
            method: Issued
        - handler: handleVestingVestingUpdated
          kind: substrate/EventHandler
          filter:
            module: vesting
            method: VestingUpdated
        - handler: handleVestingVestingCompleted
          kind: substrate/EventHandler
          filter:
            module: vesting
            method: VestingCompleted
        - handler: salp
          kind: substrate/BlockHandler
        - handler: salpContribution
          kind: substrate/BlockHandler