specVersion: 0.2.0
name: bifrost-subql
version: 1.0.0
description: ''
repository: 'https://github.com/bifrost-finance/bifrost-subql.git'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xf76d68a4c4559de22197fc09d444c9e539748f5e29db723a344a2aad495f2a2d'
  endpoint: 'wss://bifrost-rpc.devnet.liebi.com/ws'
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: vtokenMinting
          kind: substrate/BlockHandler
        - handler: handleVtokenMintingMinted
          kind: substrate/CallHandler
          filter:
            module: vtokenMinting
            method: mint
            success: true
        - handler: handleVtokenMintingMinted
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batchAll
            success: true
        - handler: handleVtokenMintingRedeemed
          kind: substrate/CallHandler
          filter:
            module: vtokenMinting
            method: redeem
            success: true
        - handler: handleVtokenMintingRedeemed
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batchAll
            success: true
        - handler: handleVtokenMintingRebondedByUnlockId
          kind: substrate/CallHandler
          filter:
            module: vtokenMinting
            method: rebondByUnlockId
        - handler: handleVtokenMintingRedeemedTransferred
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred
        - handler: handleVKSMSwap
          kind: substrate/EventHandler
          filter:
            module: zenlinkProtocol
            method: AssetSwap
        - handler: handleCurrenciesTransferred
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred
        - handler: handleVtokenRedeemedSuccess
          kind: substrate/EventHandler
          filter:
            module: vtokenMinting
            method: RedeemSuccess