specVersion: 0.2.0
name: bifrost-subql
version: 1.0.0
description: ''
repository: 'https://github.com/bifrost-finance/bifrost-subql.git'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x36441eb0da2f4b9fb2a0306db1ac31efa34f2d09b3f30d106b131febe1979004'
  endpoint: 'wss://bifrost-rpc.testnet.liebi.com/ws'
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: parachainStaking
          kind: substrate/BlockHandler
        - handler: handleParachainStakingRewarded
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: Rewarded