specVersion: 0.2.0
name: bifrost-subql
version: 1.0.0
description: ''
repository: 'https://github.com/bifrost-finance/bifrost-subql.git'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x28a92c0b05f7fedb20da73f8662976410d3826e40783b1f17fc575c03c42fad1'
  endpoint: 'wss://bifrost-rpc.prod-test.liebi.com/ws'
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: vtokenMinting
          kind: substrate/BlockHandler
        - handler: handleVtokenMintingMinted
          kind: substrate/CallHandler
          filter:
            module: vtokenMinting
            method: mint
            success: true
        - handler: handleVtokenMintingMinted
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batchAll
            success: true
        - handler: handleVKSMSwap
          kind: substrate/EventHandler
          filter:
            module: zenlinkProtocol
            method: AssetSwap
        - handler: handleCurrenciesTransferred
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred