specVersion: 1.0.0
name: bifrost-subql
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: This SubQuery project can be use as a starting point for bifrost network
repository: "https://github.com/bifrost-finance/bifrost-subql.git"
schema:
  file: ./schema.graphql
network:
#  chainId: "0x9f28c6a68e0fc9646eff64935684f6eeeece527e37bbe1f213d22caa1d9d6bed"
#  endpoint: "wss://bifrost-parachain.api.onfinality.io/public-ws"
  chainId: "0x5e40ebe7e3fa1408a5ff66fee32d9a145d86791f927e085ab72e72c8740b1c68"
  endpoint: "wss://bifrost.bifrost-staking-test.liebi.com/ws"
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleStakingErapaid
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: NewRound
        - kind: substrate/EventHandler
          handler: handleStakingReward
          filter:
            module: parachainStaking
            method: Rewarded