specVersion: 0.2.0
name: bifrost-subql
version: 1.0.0
description: ''
repository: git@github.com:bifrost-finance/bifrost-subql.git
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x9f28c6a68e0fc9646eff64935684f6eeeece527e37bbe1f213d22caa1d9d6bed'
  endpoint: wss://bifrost-rpc.liebi.com/ws
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1504966
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleParachainStakingRewarded
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: Rewarded
        - handler: handleScheduleRevokeDelegation
          kind: substrate/CallHandler
          filter:
            module: parachainStaking
            method: scheduleRevokeDelegation
        - handler: handleDelegatorBondMore
          kind: substrate/CallHandler
          filter:
            module: parachainStaking
            method: delegatorBondMore
        - handler: handleExecuteDelegationRequest
          kind: substrate/CallHandler
          filter:
            module: parachainStaking
            method: executeDelegationRequest
